apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: express-ns
data:
  DB_URI: "mongodb+srv://stforta1_db_user:8RJF2qUUJoAVkthq@cluster0.zqvwnhm.mongodb.net/?appName=Cluster0"
  ARCJET_KEY: "ajkey_01k6jyd7w6f61r7y5ycg4r09jk"
  ARCJET_ENV: "production"
  QSTASH_TOKEN: "eyJVc2VySUQiOiJkZWZhdWx0VXNlciIsIlBhc3N3b3JkIjoiZGVmYXVsdFBhc3N3b3JkIn0="
  QSTASH_URL: "https://qstash.upstash.io"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: express-ns
type: Opaque
data:
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
  API_KEY: c3VwZXItc2VjcmV0LWFwaS1rZXk=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: express-ns
data:
  #VITE_API_BASE_URL: http://localhost:3000/api/v1
